name: Docker tests

on:
  push:
  pull_request:

jobs:
  docker-tests:
    runs-on:
      ubuntu-latest:
    steps:
      - uses: actions/checkout@v3

      - uses: armn3t/docker-compose-action@v1.3.0
        with:
          compose-file: ./docker-compose.yaml
          test-command: "docker compose exec app cargo test"

