services:
  app:
    build: .
    environment:
      - DATABASE_URL=postgres://db_user:secret@db_host:5432/app_db
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    depends_on:
      - db_host
    command: bash -c "cargo install cargo-watch && cargo watch -x run"