version: '3.3'

services:
  db_host:
    image: postgres:latest
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=app_db
    command: ['postgres', '-c', 'log_statement=all']
    ports:
      - '5432:5432'
  redis:
    image: redis:latest
