version: '3.3'

services:
  app:
    build: .
    environment:
      - DATABASE_URL=postgres://db_user:secret@db_host:5432/app_db
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command: cargo watch -x run
