name: Docker tests
run-name: ${{ github.actor }} is running integration tests for axum-srv 🚀

on:
  push:
  pull_request:

jobs:
  Docker-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: ./docker-compose.yaml
          test-command: "docker compose exec app cargo test"

