name: Docker tests
run-name: ${{ github.actor }} is running integration tests for axum-srv 🚀

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Docker-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - name: Run Cargo Check
        run: cargo check
      
      # - name: Start App with docker-compose
      #   run: docker compose up -d

      # - name: Install DB checker
      #   run: sudo apt-get update && sudo apt-get install -y postgresql-client-15

      # - name: Run db migrations
      #   run: docker compose exec -T app diesel migration run
 
      # - name: Run Tests
      #   run: docker compose exec app cargo test